### ISSUE TITLE
Why use gulp?

### ISSUE THREAD

**Issue by lucasvazq** [M-Nasab/react-gulp-webpack-boilerplate#1]
Why use gulp if u have webpack?
I have seen this question several times, webpack can replace gulp.
Why u use gulp here?

**Comment by M-Nasab** [comment]
Yes, you're right. One of these, Gulp or Webpack, suffices to do all the tasks and there is no need to use them together. Mostly it's a matter of taste which one you choose.
Here it was easier for me to use Webpack to do JS related tasks, but I preferred Gulp for all the other tasks.
